In [2]:
# SE IMPORTA DATASET https://residus.gencat.cat/es/consultes_i_tramits_-_nou/estadistiques/
# ANALIZAR Y MANIPULAR DATOS PARA DEJAR LIMPIO DATASET PARA PREDICCIÓN CATALUÑA RESIDUOS.

In [3]:
# IMPORTAR BIBLIOTECA PANDAS PARA MANIPULACIÓN Y ANÁLISIS DATOS.
import pandas as pd

In [59]:
# CREAR DATAFRAME DEL DOCUMENTO CSV. 
df = pd.read_csv('Dataset_CAT_sucio_archivo.csv')
df.head(1)

,Any,Codi municipi,Municipi,Comarca,Població,Autocompostatge,Matèria orgànica,Poda i jardineria,Paper i cartró,Vidre,...,Kg/hab/any recollida selectiva,Resta a Dipòsit,Resta a Incineració,Resta a Tractament Mecànic Biològic,Resta (sense desglossar),Suma Fracció Resta,F.R. / R.M. %,Generació Residus Municipal Totals,Kg / hab / dia,Kg / hab / any
0,2000,430017.0,Aiguamúrcia,Alt Camp,614,NaN,0.0,0.0,12.51,37.0,...,86.92,NaN,NaN,NaN,417.61,417.61,88.67,470.98,2.1,767.07

In [60]:
# FILAS Y COLUMNAS
df.shape

(20843, 33)

In [34]:
# ANALISIS GENERAL DEL DATASET.
df.describe()

,Any,Codi municipi,Població,Autocompostatge,Matèria orgànica,Poda i jardineria,Paper i cartró,Vidre,Envasos lleugers,Residus voluminosos + fusta,...,Kg/hab/any recollida selectiva,Resta a Dipòsit,Resta a Incineració,Resta a Tractament Mecànic Biològic,Resta (sense desglossar),Suma Fracció Resta,F.R. / R.M. %,Generació Residus Municipal Totals,Kg / hab / dia,Kg / hab / any
count,20843.000000,20821.000000,2.084300e+04,9479.000000,20843.000000,20843.000000,20843.000000,20843.000000,20843.000000,20843.000000,...,20843.000000,17055.000000,17055.000000,17055.000000,5684.000000,20843.000000,20843.000000,20843.000000,20843.000000,20843.000000
mean,2010.502951,211817.084914,7.643853e+03,6.811942,321.321997,87.160225,356.936843,173.986334,120.007246,189.028033,...,172.336442,1215.130292,408.403415,991.500687,2112.172306,2715.779829,67.732977,4155.037319,1.527464,557.526138
std,6.344826,125157.990326,5.523111e+04,18.175427,3132.066349,431.304825,4767.357105,1494.094830,818.648772,1265.418968,...,121.564332,7202.365178,4821.472063,11318.288956,18627.450652,19172.805710,19.373506,28017.508585,0.649246,236.983829
min,2000.000000,80018.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,-0.140000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2005.000000,82397.000000,3.110000e+02,0.000000,0.000000,0.000000,8.030000,8.995000,4.010000,0.340000,...,84.970000,39.655000,0.000000,0.000000,0.000000,104.305000,55.500000,162.725000,1.150000,419.375000
50%,2011.000000,171753.000000,9.110000e+02,0.000000,13.350000,0.020000,23.210000,23.510000,13.290000,8.900000,...,151.550000,148.460000,0.000000,0.000000,133.715000,298.410000,70.170000,459.430000,1.370000,499.200000
75%,2016.000000,252075.000000,3.519000e+03,6.900000,131.005000,21.285000,101.345000,82.815000,55.505000,63.510000,...,229.180000,614.500000,0.000000,0.000000,700.872500,1257.175000,83.040000,1974.435000,1.700000,619.530000
max,2021.000000,439076.000000,1.664182e+06,326.400000,128393.620000,13457.290000,178024.000000,62326.000000,27092.150000,51485.300000,...,2209.660000,409294.200000,223740.820000,450676.610000,690308.000000,690308.000000,100.000000,902356.180000,8.720000,3183.920000

In [35]:
# ANALIZAR COLUMNAS Y TIPOS DE VARIABLE.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20843 entries, 0 to 20842
Data columns (total 33 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Any                                  20843 non-null  int64
 1   Codi municipi                        20821 non-null  float64
 2   Municipi                             20843 non-null  object
 3   Comarca                              20843 non-null  object
 4   Població                             20843 non-null  int64
 5   Autocompostatge                      9479 non-null   float64
 6   Matèria orgànica                     20843 non-null  float64
 7   Poda i jardineria                    20843 non-null  float64
 8   Paper i cartró                       20843 non-null  float64
 9   Vidre                                20843 non-null  float64
 10  Envasos lleugers                     20843 non-null  float64
 11  Residus voluminosos + fusta          20843 non-null  float64
 12  RAEE                                 11373 non-null  float64
 13  Ferralla                             9479 non-null   float64
 14  Olis vegetals                        9479 non-null   float64
 15  Tèxtil                               18949 non-null  float64
 16  Runes                                10426 non-null  float64
 17  Residus en Petites Quantitats (RPQ)  10426 non-null  float64
 18  Piles                                20835 non-null  float64
 19  Medicaments                          20835 non-null  float64
 20  Altres recollides selectives         20837 non-null  float64
 21  Total Recollida Selectiva            20843 non-null  float64
 22  R.S. / R.M. % total                  20843 non-null  float64
 23  Kg/hab/any recollida selectiva       20843 non-null  float64
 24  Resta a Dipòsit                      17055 non-null  float64
 25  Resta a Incineració                  17055 non-null  float64
 26  Resta a Tractament Mecànic Biològic  17055 non-null  float64
 27  Resta (sense desglossar)             5684 non-null   float64
 28  Suma Fracció Resta                   20843 non-null  float64
 29  F.R. / R.M. %                        20843 non-null  float64
 30  Generació Residus Municipal Totals   20843 non-null  float64
 31  Kg / hab / dia                       20843 non-null  float64
 32  Kg / hab / any                       20843 non-null  float64
dtypes: float64(29), int64(2), object(2)
memory usage: 5.2+ MB

In [36]:
df.shape

(20843, 33)

In [37]:
# COMPROBAR SI HAY NULOS EN EL DATASET. 
df.isnull().sum()

Any                                        0
Codi municipi                             22
Municipi                                   0
Comarca                                    0
Població                                   0
Autocompostatge                        11364
Matèria orgànica                           0
Poda i jardineria                          0
Paper i cartró                             0
Vidre                                      0
Envasos lleugers                           0
Residus voluminosos + fusta                0
RAEE                                    9470
Ferralla                               11364
Olis vegetals                          11364
Tèxtil                                  1894
Runes                                  10417
Residus en Petites Quantitats (RPQ)    10417
Piles                                      8
Medicaments                                8
Altres recollides selectives               6
Total Recollida Selectiva                  0
R.S. / R.M. % total                        0
Kg/hab/any recollida selectiva             0
Resta a Dipòsit                         3788
Resta a Incineració                     3788
Resta a Tractament Mecànic Biològic     3788
Resta (sense desglossar)               15159
Suma Fracció Resta                         0
F.R. / R.M. %                              0
Generació Residus Municipal Totals         0
Kg / hab / dia                             0
Kg / hab / any                             0
dtype: int64

In [38]:
# VERIFICAR SI HAY DATOS DUPLICADOS, EN ESTE CASO NO.
df.duplicated().sum()

0

In [39]:
# SE ELIMINAN COLUMNAS NO DESEADAS.
columnas_a_eliminar = ["Codi municipi","Municipi","Comarca","Autocompostatge","Poda i jardineria","Residus voluminosos + fusta","RAEE","Ferralla","Olis vegetals","Tèxtil","Runes","Residus en Petites Quantitats (RPQ)", "Piles","Medicaments","Altres recollides selectives","Resta a Dipòsit","Resta a Incineració", "Resta a Tractament Mecànic Biològic","Resta (sense desglossar)",'R.S. / R.M. % total','F.R. / R.M. %']
df.drop(columnas_a_eliminar, axis=1, inplace=True)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20843 entries, 0 to 20842
Data columns (total 12 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Any                                 20843 non-null  int64
 1   Població                            20843 non-null  int64
 2   Matèria orgànica                    20843 non-null  float64
 3   Paper i cartró                      20843 non-null  float64
 4   Vidre                               20843 non-null  float64
 5   Envasos lleugers                    20843 non-null  float64
 6   Total Recollida Selectiva           20843 non-null  float64
 7   Kg/hab/any recollida selectiva      20843 non-null  float64
 8   Suma Fracció Resta                  20843 non-null  float64
 9   Generació Residus Municipal Totals  20843 non-null  float64
 10  Kg / hab / dia                      20843 non-null  float64
 11  Kg / hab / any                      20843 non-null  float64
dtypes: float64(10), int64(2)
memory usage: 1.9 MB

In [41]:
#DESPUÉS DE ELIMINAR COLUMNAS YA NO HAY NULOS.
df.isnull().sum()

Any                                   0
Població                              0
Matèria orgànica                      0
Paper i cartró                        0
Vidre                                 0
Envasos lleugers                      0
Total Recollida Selectiva             0
Kg/hab/any recollida selectiva        0
Suma Fracció Resta                    0
Generació Residus Municipal Totals    0
Kg / hab / dia                        0
Kg / hab / any                        0
dtype: int64

In [42]:
df.head(1)

,Any,Població,Matèria orgànica,Paper i cartró,Vidre,Envasos lleugers,Total Recollida Selectiva,Kg/hab/any recollida selectiva,Suma Fracció Resta,Generació Residus Municipal Totals,Kg / hab / dia,Kg / hab / any
0,2000,614,0.0,12.51,37.0,3.83,53.37,86.92,417.61,470.98,2.1,767.07

In [43]:
#SE AGRUPAN RESULTADOS POR AÑOS Y SE SUMAN TODOS LOS MUNICIPIOS PARA OBTENER DATOS DE CATALUÑA EN GENERAL.
sum_columnas = ['Població', 'Matèria orgànica', 'Paper i cartró', 'Vidre', 'Envasos lleugers', 'Total Recollida Selectiva', 'Suma Fracció Resta', 'Generació Residus Municipal Totals']
mean_columnas = ['Kg/hab/any recollida selectiva', 'Kg / hab / dia', 'Kg / hab / any']

df_sum = df.groupby(df['Any'])[sum_columnas].sum().round(2)
df_mean = df.groupby(df['Any'])[mean_columnas].mean().round(2)
df_resultado = pd.concat([df_sum, df_mean], axis=1)

In [44]:
df_resultado.head(1)

,Població,Matèria orgànica,Paper i cartró,Vidre,Envasos lleugers,Total Recollida Selectiva,Suma Fracció Resta,Generació Residus Municipal Totals,Kg/hab/any recollida selectiva,Kg / hab / dia,Kg / hab / any
Any,,,,,,,,,,,
2000,6090040,28385.82,155369.71,76137.79,20395.33,485070.86,2990154.98,3475225.83,62.33,1.66,605.84

In [45]:
#SE AÑADEN DOS COLUMNAS NUEVAS.
df_resultado = df_resultado.assign(RS_RC_porcentaje_total=(df_resultado['Total Recollida Selectiva'] / df_resultado['Generació Residus Municipal Totals']) * 100).round(2)
df_resultado = df_resultado.assign(FR_RC_porcentaje_total=(df_resultado['Suma Fracció Resta'] / df_resultado['Generació Residus Municipal Totals']) * 100).round(2)

In [46]:
df_resultado.head(1)

,Població,Matèria orgànica,Paper i cartró,Vidre,Envasos lleugers,Total Recollida Selectiva,Suma Fracció Resta,Generació Residus Municipal Totals,Kg/hab/any recollida selectiva,Kg / hab / dia,Kg / hab / any,RS_RC_porcentaje_total,FR_RC_porcentaje_total
Any,,,,,,,,,,,,,
2000,6090040,28385.82,155369.71,76137.79,20395.33,485070.86,2990154.98,3475225.83,62.33,1.66,605.84,13.96,86.04

In [47]:
# CAMBIAR NOMBRES DE COLUMNAS. 
df_resultado.rename(columns={'Població': 'Població Catalunya', 'Generació Residus Municipal Totals': 'Generació Residus CAT Totals','RS_RC_porcentaje_total':'RS / RC % Total','FR_RC_porcentaje_total':'FR / RC % Total','Suma Fracció Resta': 'Total Fracció Resta'}, inplace=True)

In [48]:
df_resultado.head(1)

,Població Catalunya,Matèria orgànica,Paper i cartró,Vidre,Envasos lleugers,Total Recollida Selectiva,Total Fracció Resta,Generació Residus CAT Totals,Kg/hab/any recollida selectiva,Kg / hab / dia,Kg / hab / any,RS / RC % Total,FR / RC % Total
Any,,,,,,,,,,,,,
2000,6090040,28385.82,155369.71,76137.79,20395.33,485070.86,2990154.98,3475225.83,62.33,1.66,605.84,13.96,86.04

In [49]:
#REORDENAR COLUMNAS.
df_resultado = df_resultado[['Població Catalunya', 'Matèria orgànica', 'Paper i cartró', 'Vidre','Envasos lleugers','Total Recollida Selectiva','Kg/hab/any recollida selectiva','Total Fracció Resta','Generació Residus CAT Totals','RS / RC % Total','FR / RC % Total','Kg / hab / dia','Kg / hab / any']]

In [50]:
df_resultado.head(1)

,Població Catalunya,Matèria orgànica,Paper i cartró,Vidre,Envasos lleugers,Total Recollida Selectiva,Kg/hab/any recollida selectiva,Total Fracció Resta,Generació Residus CAT Totals,RS / RC % Total,FR / RC % Total,Kg / hab / dia,Kg / hab / any
Any,,,,,,,,,,,,,
2000,6090040,28385.82,155369.71,76137.79,20395.33,485070.86,62.33,2990154.98,3475225.83,13.96,86.04,1.66,605.84

In [51]:
df_resultado.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22 entries, 2000 to 2021
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Població Catalunya              22 non-null     int64
 1   Matèria orgànica                22 non-null     float64
 2   Paper i cartró                  22 non-null     float64
 3   Vidre                           22 non-null     float64
 4   Envasos lleugers                22 non-null     float64
 5   Total Recollida Selectiva       22 non-null     float64
 6   Kg/hab/any recollida selectiva  22 non-null     float64
 7   Total Fracció Resta             22 non-null     float64
 8   Generació Residus CAT Totals    22 non-null     float64
 9   RS / RC % Total                 22 non-null     float64
 10  FR / RC % Total                 22 non-null     float64
 11  Kg / hab / dia                  22 non-null     float64
 12  Kg / hab / any                  22 non-null     float64
dtypes: float64(12), int64(1)
memory usage: 2.4 KB

In [52]:
# CAMBIAR EL TIPO DE VARIABLE DE FLOAT A INT. 
df_resultado['Matèria orgànica'] = df_resultado['Matèria orgànica'].astype('int64')
df_resultado['Paper i cartró'] = df_resultado['Paper i cartró'].astype('int64')
df_resultado['Vidre'] = df_resultado['Vidre'].astype('int64')
df_resultado['Envasos lleugers'] = df_resultado['Envasos lleugers'].astype('int64')
df_resultado['Total Recollida Selectiva'] = df_resultado['Total Recollida Selectiva'].astype('int64')
df_resultado['Total Fracció Resta'] = df_resultado['Total Fracció Resta'].astype('int64')
df_resultado['Generació Residus CAT Totals'] = df_resultado['Generació Residus CAT Totals'].astype('int64')

In [53]:
df_resultado.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22 entries, 2000 to 2021
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Població Catalunya              22 non-null     int64
 1   Matèria orgànica                22 non-null     int64
 2   Paper i cartró                  22 non-null     int64
 3   Vidre                           22 non-null     int64
 4   Envasos lleugers                22 non-null     int64
 5   Total Recollida Selectiva       22 non-null     int64
 6   Kg/hab/any recollida selectiva  22 non-null     float64
 7   Total Fracció Resta             22 non-null     int64
 8   Generació Residus CAT Totals    22 non-null     int64
 9   RS / RC % Total                 22 non-null     float64
 10  FR / RC % Total                 22 non-null     float64
 11  Kg / hab / dia                  22 non-null     float64
 12  Kg / hab / any                  22 non-null     float64
dtypes: float64(5), int64(8)
memory usage: 2.4 KB

In [54]:
df_resultado.head(1)

,Població Catalunya,Matèria orgànica,Paper i cartró,Vidre,Envasos lleugers,Total Recollida Selectiva,Kg/hab/any recollida selectiva,Total Fracció Resta,Generació Residus CAT Totals,RS / RC % Total,FR / RC % Total,Kg / hab / dia,Kg / hab / any
Any,,,,,,,,,,,,,
2000,6090040,28385,155369,76137,20395,485070,62.33,2990154,3475225,13.96,86.04,1.66,605.84

In [55]:
# SE ELIMINAN MÁS COLUMNAS PARA DEJAR MÁS LIMPIO EL DATASET.
df_resultado.drop(['Matèria orgànica','Paper i cartró','Vidre','Envasos lleugers', 'Kg/hab/any recollida selectiva', 'Kg / hab / dia', 'Kg / hab / any'],axis=1,inplace=True)

In [56]:
df_resultado.head(2)

,Població Catalunya,Total Recollida Selectiva,Total Fracció Resta,Generació Residus CAT Totals,RS / RC % Total,FR / RC % Total
Any,,,,,,
2000,6090040,485070,2990154,3475225,13.96,86.04
2001,6090040,603675,2979879,3583554,16.85,83.15

In [57]:
# ANALISIS GENERAL DEL DATASET LIMPIO.
df_resultado.describe()

,Població Catalunya,Total Recollida Selectiva,Total Fracció Resta,Generació Residus CAT Totals,RS / RC % Total,FR / RC % Total
count,2.200000e+01,2.200000e+01,2.200000e+01,2.200000e+01,22.000000,22.000000
mean,7.241856e+06,1.363565e+06,2.572954e+06,3.936520e+06,34.469545,65.530455
std,5.185472e+05,3.877432e+05,3.477069e+05,2.551420e+05,9.367518,9.367518
min,6.090040e+06,4.850700e+05,2.149095e+06,3.475225e+06,13.960000,53.370000
25%,7.030079e+06,1.257081e+06,2.265054e+06,3.724416e+06,29.820000,59.625000
50%,7.510244e+06,1.444756e+06,2.446676e+06,3.975614e+06,38.070000,61.930000
75%,7.554649e+06,1.625466e+06,2.958132e+06,4.175114e+06,40.375000,70.180000
max,7.780479e+06,1.877615e+06,3.080497e+06,4.300509e+06,46.630000,86.040000

In [32]:
# GUARDAR EL DATAFRAME EN UN ARCHIVO CSV
df_resultado.to_csv('Dataset_CAT_Limpio.csv', index=True)